revert actions/configure-pages to v3 in jekyll.yml
When I changed 'actions/configure-pages@v3' to 'actions/configure-pages@v4' I got the followuing building error:

Download immutable action package 'actions/configure-pages@v4'
  Version: 4.0.0
  Digest: sha256:95f920ee91072a3e9596eff2a708d14f0fefa72b4770cbf7902965dfc6b8de4c
  Source commit SHA: 1f0c5cde4bc74cd7e1254d0cb4de8d49e9068c7d
Error: Missing download info for actions/upload-pages-artifact@v4

Hence I moving this back to v3. I changed it because I was trying to fix the error:

Error: Missing download info for actions/upload-artifact@v3

But I think that is caused by 'actions/upload-pages-artifact@v1'